# Generated by Django 4.0.1 on 2022-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(choices=[('закалённое в боях', 'bs'), ('поношенное', 'ww'), ('после полевых испытаний', 'ft'), ('немного поношенное', 'mw'), ('прямо с завода', 'fn')], max_length=30)),
                ('item_float', models.FloatField()),
                ('item_type', models.CharField(choices=[('снайперская винтовка', 'sniper'), ('штурмовая винтовка', 'rifle'), ('пистолет-пулемёт', 'smg'), ('пистолет', 'pistol'), ('нож', 'knife'), ('перчатки', 'gloves'), ('дробовик', 'shotgun'), ('прочее', 'other')], max_length=30)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='shopmanage/images')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('buyer_id', models.BigIntegerField()),
                ('buyer_link', models.CharField(max_length=150)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('feedback_rate', models.CharField(max_length=20)),
                ('feedback_text', models.CharField(max_length=150)),
                ('purchased', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
