# Generated by Django 4.0.1 on 2022-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanage', '0002_alter_users_feedback_rate_alter_users_feedback_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trade_link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
